name: Build binaries

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
      - '.github/**/*.md'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/FUNDING.yml'
      - '.github/**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:20240702
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
              git clone https://github.com/GRRLIB/GRRLIB
              dkp-pacman --sync --needed --noconfirm libfat-ogc ppc-libpng ppc-freetype ppc-libjpeg-turbo
              cd GRRLIB/GRRLIB
              make clean all install
              echo "[nez-wii]" >> /opt/devkitpro/pacman/pacman.conf
              echo "SigLevel = Never" >> /opt/devkitpro/pacman/pacman.conf
              echo "Server = https://wii.nezbednik.eu.org" >> /opt/devkitpro/pacman/pacman.conf
              cat /opt/devkitpro/pacman/pacman.conf
              ls /opt/devkitpro/pacman
              dkp-pacman --sync --needed --noconfirm ppc-jansson wii-winyl
        
      - name: Compile
        run: make
